Fix Genesis Block Creation
Sawtooth 1.2.3 apparently now requires the consensus algorithm and mode
to be specified. The message showing the regression is:

```
Error: The following setting(s) are required at genesis,
but were not included in the genesis batches:
['sawtooth.consensus.algorithm.name', 'sawtooth.consensus.algorithm.version']
```

Signed-off-by: danintel <daniel.anderson@intel.com>