Fix Protobuf Error with serialized_options
Error was:
TypeError: __new__() got an unexpected keyword argument 'serialized_options'
This requires Protobuf 3.6.0 or above to support serialized_options,
but repo.sawtooth.me is only at Protobuf 3.4.1 for Sawtooth 1.0 and 1.1 at least.

The fix is to remove the unsupported serialized_options argument.

Signed-off-by: danintel <daniel.anderson@intel.com>